version: '2'

services:
  nodejs1:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "18080:8080"

  nodejs2:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "18081:8080"
